### ISSUE TITLE
Chroot into script

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/gebuilder#14]
In order to ease chrooing into failed or incomplete builds, I'd like to have a standalone-executable script which automatically handles all of the mounts, chroots, and also runs the recommended environment updates once in the chroot:

```
root #chroot /mnt/mychroot /bin/bash
root #source /etc/profile
root #env-update
root #export PS1="(chroot) $PS1"
```

@Doeme, is there any way to call mounts and commands inside the chroot via the same script?

**Comment by Doeme** [comment]
I pushed a shell subcommand that tries to do exactly this. The branch is long gone now, but it is the proper way to handle it.

**Comment by TheChymera** [comment]
You mean [this](https://github.com/IBT-FMI/gebuilder/commit/9e802e58ff59d157bbdd34d0df694dacf17812ae) ? The code is still in the relevant scripts, but it doesn't seem to do anything. I was thinking of a script you can just call manually. But making the drop-to-action-shell work would also be an alternative.

**Comment by Doeme** [comment]
This code works perfectly here, the problem is that the shell opened does not really have a (vt-100) terminal, hence it does not display the usual PS1

**Comment by Doeme** [comment]
A fix for that issue was pushed, the recommended procedure can be added before the call to "bash" in 10-shell.sh.nolog.chroot
