### ISSUE TITLE
No image with an ID of '' exists.

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/gebuilder#27]
So I ran into this issue:

```
Deleting old image with uuid                                                                            
No image with an ID of '' exists.                                                                       
Exiting                                                                                                 
Cleaning up                                                                                             
executing losetup -d /dev/loop0                                                                         
Cleaning up after error  
```

 which could be solved by:

```
rm /usr/share/gebuilder/roots/stemgentoo/registry/openstack_image
```

Apparently this was caused by a previous attempt at `gebuild stemgentoo openstack_image` which failed without writing to but after creating the `<ID>/registry/openstack_image` file. Any idea why this can happen at all? As I understand [the relevant code](https://github.com/IBT-FMI/gebuilder/blob/bf8e7c6dcee795cff239b5fef98579376730b8ee/gebuilder/example_hooks/openstack_image/60-upload_image.sh#L27) the file should only be created when we write to it.

**Comment by Doeme** [comment]
Ah, ok, yes, the file file is created as soon as the glance-command is executed, independant of its success or failure (or if something is written to it)

It probably would be best to write the information to another file, and mv it on success

**Comment by TheChymera** [comment]
Thanks :)
