### ISSUE TITLE
package.accept_keywords support

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/gebuilder#29]
As the ebuilds required for SAMRI have been moved out of the black market and into Gentoo Science, I had to introduce [a couple of hard masks](https://github.com/gentoo/sci/blob/d6caf43906b82494ac010276b3b79769cc8e5f79/profiles/package.mask#L33) to maintain some level of stability.

Consequently, as far as I can tell there are now a few more unmasks which need to be declared to make SAMRI emergeable:

```
me@myhost ~ $ cat /etc/portage/package.accept_keywords 
=sci-biology/afni-18.1.04 **
=sci-biology/samri-9999 **
me@myhost ~ $ cat /etc/portage/package.unmask 
# required by samri (argument)
# /home/hioanas/gentoo/var/lib/overlays/science/profiles/package.mask:
# Horea Christian <horea.christ@gmail.com> (26 Jun 2018)
# All versions depend on hard-masked sci-biology/afni.
=sci-biology/samri-9999
=sci-biology/afni-18.1.04
```

Based on the [relevant gebuilder code](https://github.com/IBT-FMI/gebuilder/blob/2767cc0c7e0f22b5f47a2b69f0de8a49fe07e0f9/gebuilder/scripts/initialize/default/01-setup_specialization.sh#L45), I notice that `package.accept_keywords` is not supported. Is that so?

**Comment by Doeme** [comment]
That's probably due to me not knowing about package.accept_keywords (neumodischer Scheiss ;)

We should add the .accept_keywords there, or maybe even replace the .keywords with it...

**Comment by TheChymera** [comment]
ok, why do you suggest *replacing* `.keywords` though? these are two separate files.

**Comment by Doeme** [comment]
Due to `man 5 portage`

> The package.accept_keywords  file is  intended  to  replace the package.keywords file, since profiles support a different form of package.keywords which modifies effective KEYWORDS (rather than ACCEPT_KEYWORDS).

**Comment by TheChymera** [comment]
:)
