### ISSUE TITLE
Parametrise installation

### ISSUE THREAD

**Issue by Doeme** [IBT-FMI/gebuilder#33]
It would be neat to have the installed files parametrised, s.t. the scripts and buildroots can be installed into an arbitrary directory.
Maybe a Makefile would be a neat way to do this, which preprocesses e.g. `gebuild.m4` with the m4 macro expander.

**Comment by TheChymera** [comment]
That's a good idea, do you think this could be used to allow unprivileged users to create subsystems (also addressing [this concern](https://github.com/IBT-FMI/gebuilder/issues/30#issuecomment-469437839))?

**Comment by Doeme** [comment]
Even though we said we'd concentrate on other things, since the manpages will be generated during install time by looking at the docstrings in the scripts/**.sh, we will need a makefile anyways.

This has been added in https://github.com/IBT-FMI/gebuilder/commit/424d741ddd1637c8e15e53520a2d0f3e616c8c8d, hence I am closing this commit.

@TheChymera You will need to update your personal -9999.ebuild, look into the .gentoo-directory for guidance (you should probably just copy the file, minus the src_unpack and plus some `inherit git-r3`)
