### ISSUE TITLE
Not auto-syncing gentoo repo?

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/gebuilder#7]
@Doeme , is there any reason we set auto-sync to no [here](https://github.com/IBT-FMI/gebuilder/blob/7560a9e7f166edf2b1c74bf42bcaf987c19c5492/gebuilder/scripts/initialize/default/02-setup_sync.sh#L12)?

**Comment by Doeme** [comment]
Yes, there was a reason, namely that we do not want the specialized systems to automatically sync the /usr/portage, because this gets bind-mounted from the stemgentoo (It's considered bad style to sync a portage repo multiple times in a row)

**Comment by TheChymera** [comment]
Ok, that makes a lot of sense, but one effect of that is, that the general-purpose OpenStack systems do not behave as expected when running e.g. `eix-sync` or `emerge --sync`. Any ideas how this can be addressed rather than requiring yet another manual configuration step when starting out with one of our images?

**Comment by Doeme** [comment]
Probably just sed it away (`'/auto-sync=no/d'`) in a `scripts/openstack_image/*.sh` step?

**Comment by TheChymera** [comment]
The commit is only a partial fix, since it's restricted to the `openstack_image` command. Ideally this would be done more generally so that it applies to all the image variants.

**Comment by Doeme** [comment]
Then we probably should sed it in in scripts/update/default/xxx.sh and away in scripts/update/default/zzz.sh

**Comment by TheChymera** [comment]
Is `emaint sync -a` in this file really the only sync we want to protect against?

**Comment by Doeme** [comment]
I think so, yes.
