### ISSUE TITLE
Btrfs guide

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/gebuilder#8]
@Doeme, could you write down the instructions for enabling btrfs management of the images? I could not find them anywhere in the docs.

**Comment by Doeme** [comment]
What do you mean? Building an image with BTRFS? We have to change a configuration variable in `roots/<ID>/conf/` or in the global configuration.

Generally, the documentation is imho an unsolved problem.
It would probably be best to add some in-line documentation to the scripts/*/*.sh files, where we can specify what configuration options we use, similar to the eclass documentation.

**Comment by TheChymera** [comment]
No, I meant setting up btrfs on an OpenStack system in order to more compactly manage images for multiple specializations. I know we did it together once and it was surprisingly easy.

**Comment by Doeme** [comment]
Ah, that basically was just growing the filesystem (it works without doing that, but is rather inefficient).

1. use fdisk or another partition tool to grow the partition (should work with deleting partition 1 and adding a new one that spans the whole disk)
2. <https://btrfs.wiki.kernel.org/index.php/UseCases#Growing>

**Comment by TheChymera** [comment]
Can I do this while the partition is active? this is my system's root partition after all:

```
bs1 /usr/share/gebuilder/scripts # df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs         10M     0   10M   0% /dev
tmpfs            16G     0   16G   0% /dev/shm
tmpfs            16G  364K   16G   1% /run
/dev/vda1        99G   19G   76G  21% /
cgroup_root      10M     0   10M   0% /sys/fs/cgroup
```

**Comment by Doeme** [comment]
Yes, thats the fancy thing about BTRFS, you can resize it online

**Comment by TheChymera** [comment]
And that also reformats it? Based on `/etc/fstab` it seems to me that the partition is ext4, and `btrfs-convert /dev/vda1` failed on account of the device being mounted.

**Comment by Doeme** [comment]
Well, was the image built with the BTRFS-configuration set?

**Comment by TheChymera** [comment]
I don't know, I just built it with `gebuild stemgentoo initialize`. The string btrfs seems to only appear in this package as a kernel option, and that is always set, but I am guessing that only controls whether the kernel could boot btrfs if the system was btrfs. Is something else happening?

**Comment by TheChymera** [comment]
When I edit `/usr/share/gebuilder/roots/stemgentoo/config/openstack.conf` to include:

```
OPENSTACK_FILESYSTEM="btrfs"
```

the openstack_image subcommand, gives me:

```
[...]
Formatting the disk with btrfs
ERROR: unrecognized filesystem feature '^64bit'
[...]
```

**Comment by TheChymera** [comment]
Also, I can't seem to boot images created with:

```
OPENSTACK_IMAGE_NAME="image_$(date "+%Y%m%d")"
OPENSTACK_ROOT_PASSWORD="t00r"
OPENSTACK_FILESYSTEM="btrfs"

#Syslinux can't handle 64bit, so we disable it.
#This has the effect, that our root partition can't grow larger than 2TB
OPENSTACK_FILESYSTEM_OPTS=""
```

![screenshot from 2018-02-19 15-11-43](https://user-images.githubusercontent.com/950524/36382125-2757f1e4-1588-11e8-85cd-6cbfab3af1c4.png)

**Comment by TheChymera** [comment]
@Doeme 

I have also tried setting:

```
scripts/openstack_image/stemgentoo/40-generate_bootchain.sh
18:      LINUX /boot/vmlinuz root=UUID=$OPENSTACK_IMG_UUID rootfstype=btrfs console=ttyS0,115200n8
24:UUID=$UUID              /               btrfs            noatime         0 1
```
since they were previously set to `ext4`, but this did not help either.

**Comment by Doeme** [comment]
Either there is no `/boot/{sys,ext}linux/{sys,ext}linux.cfg` present, or syslinux does not find the partition it has to boot from.

**Comment by TheChymera** [comment]
So it seems the file exists on the host system, but not on the stemgentoo system. Is this the issue?

```
bs1 /usr/share/gebuilder/roots/stemgentoo # stat root/boot/{sys,ext}linux/{sys,ext}linux.cfg
stat: cannot stat 'root/boot/syslinux/syslinux.cfg': No such file or directory
stat: cannot stat 'root/boot/syslinux/extlinux.cfg': No such file or directory
stat: cannot stat 'root/boot/extlinux/syslinux.cfg': No such file or directory
stat: cannot stat 'root/boot/extlinux/extlinux.cfg': No such file or directory
bs1 /usr/share/gebuilder/roots/stemgentoo # stat /boot/{sys,ext}linux/{sys,ext}linux.cfg
  File: /boot/syslinux/syslinux.cfg
  Size: 169             Blocks: 8          IO Block: 4096   regular file
Device: fe01h/65025d    Inode: 225091      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-31 03:21:39.156000000 +0000
Modify: 2018-01-31 03:21:39.156000000 +0000
Change: 2018-01-31 03:21:39.156000000 +0000
 Birth: -
stat: cannot stat '/boot/syslinux/extlinux.cfg': No such file or directory
stat: cannot stat '/boot/extlinux/syslinux.cfg': No such file or directory
stat: cannot stat '/boot/extlinux/extlinux.cfg': No such file or directory
```

**Comment by Doeme** [comment]
This file only ever exists (if at all) in the image file, so you probably have to mount it with `mount -t btrf -o loop /path/to/roots/<ID>/<cantrememberwhatgoesintohere>/image_<date> /path/to/mountpoint`

**Comment by TheChymera** [comment]
Doesn't want to mount apparently, the current system is ext4, but it has the btrfs kernel options and `btrfs-progs` installed:

```
bs1 ~ # mount -t btrf -o loop /usr/share/gebuilder/roots/stemgentoo/openstack_images/image_20180219 /mnt/debug
mount: /mnt/debug: unknown filesystem type 'btrf'.
bs1 ~ # mount -t btrfs -o loop /usr/share/gebuilder/roots/stemgentoo/openstack_images/image_20180219 /mnt/debug
mount: /mnt/debug: wrong fs type, bad option, bad superblock on /dev/loop2, missing codepage or helper program, or other error.
```

**Comment by TheChymera** [comment]
@Doeme you seem to only have enabled the main BTRFS kernel option, do you think enabling any of the sub-options might help?

```
utils/openstack_kernel.config
2243:CONFIG_BTRFS_FS=y
2244:# CONFIG_BTRFS_FS_POSIX_ACL is not set
2245:# CONFIG_BTRFS_FS_CHECK_INTEGRITY is not set
2246:# CONFIG_BTRFS_FS_RUN_SANITY_TESTS is not set
2247:# CONFIG_BTRFS_DEBUG is not set
2248:# CONFIG_BTRFS_ASSERT is not set
```

**Comment by TheChymera** [comment]
Also, the image doesn't seem to mount:

```
bs1 ~ # mount -t btrfs -o loop /usr/share/gebuilder/roots/stemgentoo/openstack_images/image_20180219 /mnt/debug
mount: /mnt/debug: wrong fs type, bad option, bad superblock on /dev/loop2, missing codepage or helper program, or other error.
```

And here's the log:

https://bpaste.net/show/d9e4694d4845

**Comment by TheChymera** [comment]
Ok, so I finally got it to mount, and `syslinux.cfg` is present:

```
bs1 ~ # losetup -D
bs1 ~ # losetup -fP --show /usr/share/gebuilder/roots/stemgentoo/openstack_images/image_20180219
/dev/loop2
bs1 ~ # mount /dev/loop2p0 /mnt/debug
mount: /mnt/debug: special device /dev/loop2p0 does not exist.
bs1 ~ # mount /dev/loop2p1 /mnt/debug
bs1 ~ # ls /mnt/debug/boot/
.keep                        config-4.9.76-gentoo-r1      initramfs-4.9.76-gentoo      vmlinuz
System.map-4.9.76-gentoo-r1  initramfs                    syslinux/                    vmlinuz-4.9.76-gentoo-r1
bs1 ~ # ls /mnt/debug/boot/syslinux/
ldlinux.c32  libcom32.c32  libutil.c32  memdisk  menu.c32  syslinux.cfg
```

**Comment by TheChymera** [comment]
Just for reference, this was all happening before and is still happening after c10997816c6788ce321a3995fa85833013939759 . And to be frank, I have no idea how btrfs could have worked before this (unless the relevant config files are outright ignored for some reason).

**Comment by TheChymera** [comment]
@Doeme I looked through the entire diff, and spotted nothing suspect:

http://bpaste.net/show/1e9c701c4e5a

Do you see anything that might be causing this issue?

**Comment by Doeme** [comment]
the rootfstype option is, I think, not critical since the kernel iterates through all available fstypes. It is, afaik, only a hint on what to try first.
The fstab should also be (somewhat) irrelevant, since the kernel has / mounted anyways, and the fstab-entry is only used for fsck or other maintenance operations.

I do not know what changed, but the process of installing the bootloader is here:

https://github.com/IBT-FMI/gebuilder/blob/master/gebuilder/scripts/openstack_image/default/40-generate_bootchain.sh

maybe look at the logfile /roots/<ID>/logs/openstack_image/40-generate_bootchain.sh.log (or similar)

**Comment by TheChymera** [comment]
I pasted the entire logs [earlier](https://github.com/IBT-FMI/gebuilder/issues/8#issuecomment-366820128), but, upon looking again, I see nothing suspicious in that (or [any other sections](http://bpaste.net/show/f904c3301793)):

```
bs1 ~ # cat /usr/share/gebuilder/roots/stemgentoo/logs/openstack_image/40-generate_bootchain.sh.log
Copying syslinux files
Installing extlinux
/usr/share/gebuilder/roots/stemgentoo/root/../mnt/boot/syslinux/ is device /dev/loop3p1
Warning: unable to obtain device geometry (defaulting to 64 heads, 32 sectors)
         (on hard disks, this is usually harmless.)
Writing bootloader, booting from UUID 87b4ee50-c18e-42e0-b832-17482d20d711
Writing fstab root-entry
Generating initramfs /usr/share/gebuilder/roots/stemgentoo/root/../mnt/boot/initramfs-4.9.76-gentoo
dracut: Executing: /usr/bin/dracut --no-kernel -m "base rootfs-block" /usr/share/gebuilder/roots/stemgentoo/root/../mnt/boot/initramfs-4.9.76-gentoo 4.9.76-gentoo
dracut: *** Including module: rootfs-block ***
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: base ***
dracut: *** Including module: fs-lib ***
dracut: *** Including modules done ***
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Store current command line parameters ***
dracut: *** Creating image file '/usr/share/gebuilder/roots/stemgentoo/mnt/boot/initramfs-4.9.76-gentoo' ***
dracut: *** Creating initramfs image file '/usr/share/gebuilder/roots/stemgentoo/mnt/boot/initramfs-4.9.76-gentoo' done ***
```

I also tried sourcing the `OPENSTACK_IMG_UUID` here (no idea if this is right, but `UUID` was in any case always empty):

```
debug "Writing fstab root-entry"
cat <<-EOF >> ${OPENSTACK_IMG_MNT}/etc/fstab
UUID=$OPENSTACK_IMG_UUID              /               $OPENSTACK_FILESYSTEM            noatime         0 1
EOF
```

And still to no avail.

**Comment by TheChymera** [comment]
While a major issue (ideally I would want to reference a working project in the pioneer fellowship submission - deadline next week), this seems unrelated to btrfs. Continued in the linked discussion.

**Comment by TheChymera** [comment]
@Doeme please have a look at whether anything is still missing from [the relevant README section](https://github.com/IBT-FMI/gebuilder#btrfs-support).
