### ISSUE TITLE
Default roots location

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/gebuilder#9]
Perhaps it would be best to implement a standard roots location.

This would help with very many things, not least of all having a standardized regular-update [cron job](https://github.com/IBT-FMI/gebuilder/blob/01fd6f76d29f246df0ac13bf20cf48b06a45e230/.gentoo/app-misc/gebuilder/files/gebuilder_global_update#L5).

Since the scenario of multiple gebuilder set-ups running on the same system is not forseeable, I think we wouldn't be burning any bridges here.

@Doeme any ideas what would be a good location?

**Comment by TheChymera** [comment]
This may also help with the current dependence on `chmod +x /root`, as seen [here](https://github.com/IBT-FMI/gebuilder#permission-error-for-specialization-ebuilds).

**Comment by Doeme** [comment]
Yep, might be a possibility. Maybe it would be best to make it configurable in /etc/gebuilder.conf?
I do not know what default location would be reasonable. Maybe the same as catalyst, i.e. `/var/tmp/gebuilder/`?

**Comment by TheChymera** [comment]
sounds good.

**Comment by Doeme** [comment]
I'd suggest cd'ing in the `/usr/bin/buildserver` script

**Comment by TheChymera** [comment]
As of d024c3262b8083dacc2751c0897c531206bba7f6 we are using `/usr/share/gebuilder/roots` as the standard roots path.
